### PR TITLE
Repo housekeeping

### PR DESCRIPTION
**Pull request by gjedlicska**
- chore(.vscode): remove .vscode folder, this should not be part of version control
- chore(.gitignore): ignore .vscode folder

### CODE REVIEW

**Comment by izzylys** [comment]
lgtm!

**Comment by izzylys** [comment]
oops reverted as it broke the tests

**Comment by gjedlicska** [comment]
💥 Ouch, let me check that.

**Comment by izzylys** [comment]
partially my fault as i didn't realise ci wasn't running for PRs from remotes 🤦 

this might be a more involved fix - ci is using an orb which does the requirements for you. it's currently using the `requirements.txt` and i'm not if poetry is an option

**Comment by gjedlicska** [comment]
There should be a solution for that, maybe something like this:
https://deployeveryday.com/2019/03/15/python-poetry-circle-ci.html

**Comment by izzylys** [comment]
yep I'm sure there is! all I meant by "ci config needs to be rethought" is just that we need to rewrite it as it's currently relying quite heavily on an orb we can no longer use

**Pull request merged**
